### ISSUE TITLE
TODO from the new GpuArray from compyte

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1444]
This is a list of thing to do for the new GpuArray. I put this here to have them all in one place.
- [x] configparam.py, move the DeviceParam to configdefault.py
- [x] sandbox/gpuarray/**init**.py remove import of BoolParam and IntParam
- [x] gpuarray/**init**.py init_dev() check for None, remove TODO
- [x] GpuFromHost.grad, add as_gpuarray_variable(gz)
- [x] HostFromGpu.c_code init (name)s_ga_s to NULL.
- [x] GpuFromHost.c_code, set error message in error handling code for new_GpyArray.
- [x] fix CudaFromGpu.**str**
- [x] Add CudaFromGpu.view_map and GpuFromCuda.view_map = {0:0}
- [x] Add CudaFromGpu.c_code_cache_version()
- [x] Add GpuAlloc.**hash** and **eq**
- [x] rebase on master and change get_constant_value and catched error
- [x]  {HostFromGpu,GpuFromHost}.c_code xdecref out
- [x] gpuarray.opt.py remove gpuarray_after_fusion
- [x] InputToGpuOptimizer.apply, replace return by continue, also for CudaNdarray opt.
- [x] GpuArrayType.get_size() and get_size_info()
- [x] theano.compile.register_view_op_c_code() in typ
- [x] Add strided tests for HostFromGpu and GpuFromHost
- [x] Add test for GpuFromCuda, CudaFromGpu, GpuAlloc and DeepCopy.
- [x] GpuAlloc.do_constant_folding()
- [x] GpuAlloc.c code
- [x] reshape support -1 as numpy. Do we copy if the input is not c contiguous in all case?
- [x] GpuAlloc memset 0.

Longer term todo:
- Gemv, gemm, work in more strided cases.
- GpuAlloc.make_node and local_gpualloc opt should not add a shape_padleft.
- move gpuarray to theano/gpuarray
- HostFromGpu, use cuda/opencl strided matrix transfer? Is that faster?
- HostFromGpu/GpuFromHost/CudaFromGpu/GpuFromCuda reuse output memory buffer
- elemwise in compute, don't reshape elemwise inputs when they don't have the same number of dimensions.
- Port the theano gemm/gemv code for c/f/random layout.
- GpuArrayType.values_eq, do the reduction on the GPU.
- DeepCopy c_code in type.py don't reuse previous outputs.
- pinned memory in the CPU to GPU and reverse case.
- review C API to be like numpy to allow to change the internal representation.
- elemwise2 don't call reshape to pad left if the ndim isn't the same
