### ISSUE TITLE
Meta Optimizers

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#2072]
Theano now provides access to several different convolution implementations that perform very differently depending on image and kernel shapes, and depending on the direction when used in training a CNN (forward pass, gradient wrt. weights, gradient wrt. inputs), but also have different restrictions (filter shapes, memory usage).
A lot could be gained by picking the best-performing implementation for each individual convolution in a CNN: https://github.com/soumith/convnet-benchmarks
Because the relative performance of different implementations heavily depends on the GPU used, it is impossible to select the optimal implementation at compile time via some clever heuristic.

So I would like to start a discussion on adding "meta optimizers" to the Theano graph optimizers. A meta optimizer would collect a set of possible replacements for an op, compile each of them, time their performance and then select the best-performing one.

This might be implemented in the form of a regular graph optimizer, but it should have the following features:
- It should operate on a list of op replacement functions that each return a replacement for a given op or a falseish value to indicate that they are not applicable -- similar to what the current graph optimizers do anyway.
- It should be possible to register additional op replacement functions with a given meta optimizer. For example, user code may want to register a wrapper for cuda-convnet, cuda-convnet2 or some other Theano-external implementation with Theano's conv2d meta optimizer.
- It should be able to cache its decisions, so that it does not need to re-run any benchmarks if it is repeatedly asked to find a replacement for a given op and device with a given set of registered replacement functions. (This cache should be as permanent as the compilation cache.)

I'm currently interested in GPU-based conv2d only. In this case the meta optimizer could spring into action for any `GpuConv` op with fully specified shape on compile time, by compiling and running a set of proposed replacements on random dummy data. Other use cases for meta-optimization may require more realistic data -- they could hijack the test value computation, for example.

Sooo...
1. What do you think of the idea in general?
2. What would it need to implement the features listed above for a GpuConv meta optimizer?
3. Should the implementation plan for possible future meta optimizers or not care about generality/reusability for now?

/Update Nov 24: A first implementation was done in #2266. TODOs left:
- [ ] The meta-optimizer currently tries all available convolutions, it should only try the ones selected via `optimizer_including` and `optimizer_excluding`
- [ ] For gemm, it should try both GpuCorrMM and GpuCorrMM_gradWeights if both are applicable, not rely on the heuristic in local_conv_gemm
- [ ] Timings should be cached on disk to speed up repeated invocations.
- [ ] The configuration flag `metaopt.verbose` should become an int: 0 for silent mode, 1 to only warn if we cannot meta-optimize some op (missing shape information), 2 for full output of separate timings and selected implementation
- [ ] Update it to try the 3 cudnn forward convolution algo.
- [ ] For 3d convolution, try conv3d() vs conv3d2d() (sometimes the last one is faster: gh-5713)

**Comment by rubenvereecken** [comment]
Quite an old discussion it seems. I got here through the [documentation page](http://deeplearning.net/software/theano/library/tensor/nnet/conv.html#theano.tensor.nnet.conv.conv2d) and [this article](http://benanne.github.io/2014/12/09/theano-metaopt.html) in the hope of squeezing some extra performance out of my program. 

I got none of the fancy output @f0k displayed in the post. Before I dig all the way into the code to see if this is still somehow supported, does anyone know if it is? This issue being open for so long scared me.

**Comment by benanne** [comment]
Note that cuDNN itself now has multiple convolution implementations (including FFT-based) and also has something like a metaoptimizer built in these days. From Theano, you can control which implementations are used with the Theano flags `dnn.conv.algo_fwd`, `dnn.conv.algo_bwd_filter` and `dnn.conv.algo_bwd_data`. For the different options, have a look at the 'notes' section in the docs: http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html (note that this is slightly outdated, the option `dnn.conv.algo_bwd` no longer exists.)

By setting all of them to 'time_once', you get similar behaviour to the metaoptimizer: it will time all implementations and use the fastest ones. If you have a recent GPU (Maxwell-based), I thoroughly recommend playing with these settings as I've seen speedups of more than 50%.

**Comment by f0k** [comment]
> Before I dig all the way into the code to see if this is still somehow supported, does anyone know if it is? This issue being open for so long scared me.

It's possible that it needs some work to resurrect since the conv2d interface was recently changed. The issue being open for so long is just because the original post on the top still has several suggestions/TODOs for improving meta-optimization over what I initially implemented.

This being said, if you have cuDNN, then the meta-optimizer probably won't buy you anything over what @benanne suggested -- it was more interesting in the early days when cuDNN was neither widely supported nor mature. And it would become interesting again if we added support for alternative implementations such as facebook's or Nervana's.

**Comment by rubenvereecken** [comment]
Thanks @benanne and @f0k, I managed to get my hands on cuDNN but was trying to see if there were any other gains to be had depending on the problem maybe. So far, with manual exploration, I've managed to get the best runtimes using cuDNN (through Lasagne's interface), so I'll stick to that.

**Comment by nouiz** [comment]
was also discussed in gh-3557. Still needed as cudnn timer don't cover our own code and don't cover mixing the forward/back-ward when possible.

**Comment by f0k** [comment]
> Still needed as cudnn timer don't cover our own code and don't cover mixing the forward/back-ward when possible.

Still a nagging problem is that it requires the shapes to be known at compile time. This makes it unusable for fully-convolutional models, for example. We could do everything at runtime (like "time_once" and "time_on_shape_change") if we had a way to directly call and time cuDNN functions and the caffe-based implementation. This in turn would require them to reside in precompiled modules, not compiled on-demand. This in turn could greatly reduce compile time for some models. That's more of a long-term idea, though :)

**Comment by nouiz** [comment]
If we implement shape inference when we build the graph, then we could do
that at compile time. This is another way to get there too.

**Comment by f0k** [comment]
> If we implement shape inference when we build the graph, then we could do that at compile time.

No, I was saying there are models for which the shape is only known at runtime. E.g., for a fully-convolutional model, the spatial dimensions may vary, and for many models, the batchsize may vary. So it makes sense to do the timing at runtime, as done for cuDNN. (Of course, if every call has a different shape, it doesn't make sense to do a `time_on_shape_change`, but the `time_once` could still help. And if we implement memoization, after a while there'll be a database of which algorithm to use when.)

**Comment by affanv14** [comment]
> For gemm, it should try both GpuCorrMM and GpuCorrMM_gradWeights if both are applicable, not rely on the heuristic in local_conv_gemm

Can you please elaborate on this.

**Comment by f0k** [comment]
> Can you please elaborate on this.

Instead of only `conv_gemm`, we should have `conv_gemm` and `conv_gemm_alternative` similar to how it's done for cuDNN. I.e., always try two versions as described here: https://github.com/Theano/Theano/pull/2266#issuecomment-63960480. The current `conv_gemm` includes a heuristic that selects between different code paths depending on the input and filter tensor shapes, this should be circumvented in the meta-optimizer to only rely on timing instead.

Note that the meta-optimizer is not integrated in the new gpu backend at all, so this would need to be done first. The new backend also has convolution placeholder Ops that explicitly encode the direction (forward, backward wrt. input, backward wrt. weights), so the set of optimizers participating in the meta-optimization needs to be changed a bit.

**Comment by vikramnitin9** [comment]
> The meta-optimizer currently tries all available convolutions, it should only try the ones selected via optimizer_including and optimizer_excluding

Regarding this, how do you access (from the meta-optimizer) the tag passed to 'optimizer_including=...' to check whether or not to include a particular optimizer?

**Comment by affanv14** [comment]
Does the Gpuarray backend require device synchronisation ? I'm a little confused about this

**Comment by f0k** [comment]
> Does the Gpuarray backend require device synchronisation ? I'm a little confused about this

Is this question about the meta-optimizer? Are you working on this? In the meta-optimizer I wrote for the old backend, I specifically compile the function such that the input and output stay on GPU. In this case, we need device synchronization to measure the computation time -- only if the result is copied to CPU there will be an implicit synchronization. I would assume it's the same for the new backend, but you can try: compile a function that computes on GPU without any gpu-to-host or host-to-gpu transfers, run it ten times and time the result, then run it ten times + synchronize in the end and time the result.

**Comment by affanv14** [comment]
> For gemm, it should try both GpuCorrMM and GpuCorrMM_gradWeights if both are applicable, not rely on the heuristic in local_conv_gemm

From what I have understood, you mean to say that GPUCorrmm_gradweight (and looking at the GPUCorrMM optimization function in opt.py, GPUCorrMM_gradInputs as well ) compute the forward pass faster under a few situations and conditions. So new optimization functions need to be created which will be passed to the meta-optimizer. Which in-turn will be used to find the fastest implementation. Am I right?

> Update it to try the 3 cudnn forward convolution algo

referring https://github.com/Theano/Theano/issues/2072#issuecomment-168751110 . Does this still need to be done?

**Comment by f0k** [comment]
> So new optimization functions need to be created which will be passed to the meta-optimizer. Which in-turn will be used to find the fastest implementation. Am I right?

Correct. In the old backend, there were optimization functions like `local_dnn_conv_alternative` (or some permutation of these words, I don't recall exactly) which tried to swap in a different implementation. See my writeup at http://benanne.github.io/2014/12/09/theano-metaopt.html for a more slow-paced explanation.

>> Update it to try the 3 cudnn forward convolution algo

> Does this still need to be done?

Yes. For the old backend, I only tried two algorithms for each convolution (the "natural" one, and an alternative), but depending on the convolution, all three might be applicable.

**Comment by affanv14** [comment]
> Yes. For the old backend, I only tried two algorithms for each convolution (the "natural" one, and an alternative), but depending on the convolution, all three might be applicable.

Oh, ok. I confused algo for the algo argument in dnn_conv, I see that you meant fwd algo, grad wrt weights and inputs. I understood now, Thanks!

**Comment by f0k** [comment]
> I confused algo for the algo argument in dnn_conv

Ah... I see. The "Update it to try the 3 cudnn forward convolution algo" was added to the TODO list by @nouiz, I actually don't know whether this referred to the different cuDNN implementations or the directions. Both is possible. Maybe this was before cuDNN provided a way to time the implementations. In any case, I would rely on cuDNN for the implementations. The meta-optimization base class times the function three times and takes the minimum, so it's okay if the first call uses cuDNN's internal meta-optimization.

**Comment by lamblin** [comment]
I think this has been done by @affanv14 during the summer. Should we close this?
