### ISSUE TITLE
Remove useless alloc/dimshuffle/reshape caused by tensor.tile

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2943]
The new implementation of `tensor.tile` as a function, rather than an Op, makes the previously-existing optimization useless.
Moreover, the new implementation supports more cases that could give rise to useless operations.
A start could be removing dimshuffles that move (or add or remove) broadcastable dimensions if it is inside a Reshape operation, or simplify dimshuffles inside a Reshape.

Currently identified optimizations:
- [x] Remove useless dimshuffle (#4071)
- [x] Replace some Alloc by DimShuffle (#4072)
- [x] Replace some Reshape by DimShuffle (#4073)
- [x] Replace some Reshape(Dimshuffle) by Reshape (#4580)
- [x] Uncanonicalize Dimshuffle inside Alloc, Reshape and Subtensor (#4647)

**Comment by nouiz** [comment]
Can you give an example that have this problem? There is already many
dimshuffle optimization (but none related to reshape I think)

How to dimshuffle inside a reshape? a reshape do not change the order of
dimensions. I don't see how this can be done.

**Comment by lamblin** [comment]
For an example, see the existing test [test_local_useless_tile](https://github.com/Theano/Theano/blob/master/theano/tensor/tests/test_opt.py#L3616).
The optimization I have in mind would be something like:
`reshape(dimshuffle{'x',0,'x',1,2,3}(var), shape) => reshape(var, shape))` since adding broadcastable dimensions did not change anything.
We could probably do even more if `var` has some broadcastable dimensions that are moved around by the dimshuffle. For instance `reshape(dimshuffle{1,0}(var), shape)` is equivalent to `reshape(var, shape)` if `var` is a `row` or a `col`.
That way, we can also get rid of the `reshape` itself if the `shape` corresponds to `var.shape`.

**Comment by mohammadpz** [comment]
An example that fails is when we call ```tile(var, (1,) * var.ndim)```. The operation is useless but the computational graph looks like:
```python
 |InplaceDimShuffle{0,1} [id B] <TensorType(float32, row)> ''   3
 | |Alloc [id C] <TensorType(float32, row)> ''   2
 |   |<TensorType(float32, vector)> [id D] <TensorType(float32, vector)>
 |   |TensorConstant{1} [id E] <TensorType(int8, scalar)>
 |   |Shape_i{0} [id F] <TensorType(int64, scalar)> ''   0
 |     |<TensorType(float32, vector)> [id D] <TensorType(float32, vector)>
 |MakeVector{dtype='int64'} [id G] <TensorType(int64, vector)> ''   1
   |Shape_i{0} [id F] <TensorType(int64, scalar)> ''   0
```
Three optimizations that must be applied in the above case are:

- ```DimShuffle{0, 1, ..., var.ndim-1}``` is useless.

- ```Alloc``` with 1 on the added dimensions or on the dimensions that are already broadcastable can be replaced ```DimShuffle{'x', 0}```

- ```Reshape((1, n))``` can be replaced by ```DimShuffle{'x', 0}```

**Comment by nouiz** [comment]
The graph is cut. We don't see the reshape. I think it is the first line that is missing.

**Comment by mohammadpz** [comment]
@nouiz , I just updated it. Thanks!

**Comment by nouiz** [comment]
The reshape optimization needed is:
reshape(row, [N]) -> Dimshuffle{0}. Here the input of reshape is a row(2d matrix where there is only 1 row) and the output is a vector.

This one is more tricky as if the shape isn't right, we don't want to remove the error. So I would do the 2 other optimization first and then check again what is the graph. If we can infer the shape is the same, the we can implement the new optimization. But if we can't infer that there is no shape error, we can't make an optimization.

**Comment by lamblin** [comment]
I added a 4th optimization that is still needed after the other ones.
