### ISSUE TITLE
Issues about cloning or replacement

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5483]
This is a meta-ticket to gather all the issues with cloning and replacement of variables.

- [ ] Misleading error message when replacing variables with "givens" #2011
  - started in PR #2758
- [ ] theano.clone does not clone random variables properly #1467
- [ ] theano.clone missing documentation #3558
- [ ] rebuild_collect_shared: max recursion limit #1795
- [ ] Inconsistent behaviour of given kw in theano.function #5482
